### ISSUE TITLE
Versión de BeautifulSoup equivocada en README.md

### ISSUE THREAD

**Issue by AlexisAndradeDev** [SandovalAguilar/mp_extractor#3]
En el README.md, "pip install BeautifulSoup" debe reemplazarse por "pip install beautifulsoup4".

Tratar de instalar BeautifulSoup en Python 3.x da el siguiente error:
"You're trying to run a very old release of Beautiful Soup under Python 3. This will not work."<>"Please use Beautiful Soup 4, available through the pip package 'beautifulsoup4'."

En htmlToDataFrame.py, de hecho, se utiliza beautifulsoup4, no BeautifulSoup.

**Comment by SandovalAguilar** [comment]
Corregido, muchas gracias.
